In [2]:
import pandas as pd
import seaborn as sbn
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

# 1. logistic regression with iris_100

### (1) Use sl & sw as explanatory variables 

In [6]:
iris = sbn.load_dataset("iris")

In [7]:
iris.columns = ['sl','sw', 'pl','pw','sp']

In [8]:
iris = iris.iloc[50:] #delete setosa 

In [9]:
iris['sp'].loc[iris['sp']=='versicolor'] = 0 #put vc = 0 & vg = 1
iris['sp'].loc[iris['sp']=='virginica'] = 1

/Users/mac/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [10]:
iris

sl   sw   pl   pw sp
50   7.0  3.2  4.7  1.4  0
51   6.4  3.2  4.5  1.5  0
52   6.9  3.1  4.9  1.5  0
53   5.5  2.3  4.0  1.3  0
54   6.5  2.8  4.6  1.5  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  1
146  6.3  2.5  5.0  1.9  1
147  6.5  3.0  5.2  2.0  1
148  6.2  3.4  5.4  2.3  1
149  5.9  3.0  5.1  1.8  1

[100 rows x 5 columns]

In [11]:
Xvar_1 = sm.add_constant(iris[['sl', 'sw']])
yvar = iris['sp']

In [12]:
Xvar_1['sw'].dtype

dtype('float64')

In [13]:
yvar.apply(float)

50     0.0
51     0.0
52     0.0
53     0.0
54     0.0
      ... 
145    1.0
146    1.0
147    1.0
148    1.0
149    1.0
Name: sp, Length: 100, dtype: float64

In [14]:
yvar = yvar.apply(float)

In [248]:
model_1 = sm.Logit(yvar, Xvar_1)

In [249]:
res_1 = model.fit()

Optimization terminated successfully.
         Current function value: 0.551629
         Iterations 6


In [250]:
res_1.params

const   -13.046030
sl        1.902375
sw        0.404659
dtype: float64

In [251]:
res_1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       97
Method:                           MLE   Df Model:                            2
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.2042
Time:                        22:13:13   Log-Likelihood:                -55.163
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 7.144e-07
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -13.0460      3.097     -4.212      0.000     -19.117      -6.975
sl             1.9024      0.517      3.680      0.000       0.889       2.916
sw             0.4047      0.863      0.469      0.639      -1.286       2.096
==============================================================================
"""

In [252]:
predict_1 = np.where(res_1.predict(Xvar_1)>=0.5,1,0)

In [253]:
predict_1

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [255]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(yvar,predict_1))
print(classification_report(yvar,predict_1))

[[38 12]
 [13 37]]
              precision    recall  f1-score   support

         0.0       0.75      0.76      0.75        50
         1.0       0.76      0.74      0.75        50

    accuracy                           0.75       100
   macro avg       0.75      0.75      0.75       100
weighted avg       0.75      0.75      0.75       100



### (2) Use sl, sw and put some interaction terms using sl and sw

In [242]:
iris['sw*sl'] = iris['sw']*iris['sl']
iris['sw*sw'] = iris['sw']*iris['sw']
iris['sl*sl'] = iris['sl']*iris['sl']

In [243]:
iris

sl   sw   pl   pw sp  sw*sl  sw*sw  sl*sl
50   7.0  3.2  4.7  1.4  0  22.40  10.24  49.00
51   6.4  3.2  4.5  1.5  0  20.48  10.24  40.96
52   6.9  3.1  4.9  1.5  0  21.39   9.61  47.61
53   5.5  2.3  4.0  1.3  0  12.65   5.29  30.25
54   6.5  2.8  4.6  1.5  0  18.20   7.84  42.25
..   ...  ...  ...  ... ..    ...    ...    ...
145  6.7  3.0  5.2  2.3  1  20.10   9.00  44.89
146  6.3  2.5  5.0  1.9  1  15.75   6.25  39.69
147  6.5  3.0  5.2  2.0  1  19.50   9.00  42.25
148  6.2  3.4  5.4  2.3  1  21.08  11.56  38.44
149  5.9  3.0  5.1  1.8  1  17.70   9.00  34.81

[100 rows x 8 columns]

##### Apply all the interaction terms

In [257]:
Xvar_2 = sm.add_constant(iris[['sl', 'sw', 'sw*sl', 'sw*sw', 'sl*sl']])

In [258]:
model_2 = sm.Logit(yvar, Xvar_2)

In [259]:
res_2 = model_2.fit()

Optimization terminated successfully.
         Current function value: 0.549483
         Iterations 7


In [351]:
res_2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       94
Method:                           MLE   Df Model:                            5
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.2073
Time:                        23:11:32   Log-Likelihood:                -54.948
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 2.616e-05
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.6014     28.857      0.159      0.873     -51.958      61.161
sl            -3.0809      8.061     -0.382      0.702     -18.881      12.719
sw            -1.1778     12.954     -0.091      0.928     -26.567      24.212
sw*sl          0.3338      2.188      0.153      0.879      -3.954       4.622
sw*sw         -0.0745      2.269     -0.033      0.974      -4.522       4.373
sl*sl          0.3218      0.815      0.395      0.693      -1.275       1.919
==============================================================================
"""

In [260]:
predict_2 = np.where(res_2.predict(Xvar_2)>=0.5,1,0)

In [261]:
predict_2

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [262]:
print(confusion_matrix(yvar,predict_2))

[[38 12]
 [15 35]]


#### Use some of the interaction terms

In [263]:
Xvar_3 = sm.add_constant(iris[['sl','sw','sw*sl']])

In [264]:
model_3 = sm.Logit(yvar, Xvar_3)
res_3 = model_3.fit()

predict_3 = np.where(res_3.predict(Xvar_3)>=0.5,1,0)
predict

Optimization terminated successfully.
         Current function value: 0.550402
         Iterations 7


array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [352]:
res_3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       96
Method:                           MLE   Df Model:                            3
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.2059
Time:                        23:11:49   Log-Likelihood:                -55.040
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 2.785e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1483     26.270     -0.006      0.995     -51.636      51.340
sl            -0.1930      4.287     -0.045      0.964      -8.595       8.209
sw            -4.1454      9.316     -0.445      0.656     -22.405      14.114
sw*sl          0.7364      1.507      0.489      0.625      -2.218       3.691
==============================================================================
"""

In [265]:
print(confusion_matrix(yvar,predict_3))

[[38 12]
 [14 36]]


### (3) Use all the data (sl,sw,pl,pw) as explanatory variables 

In [267]:
Xvar_4 = sm.add_constant(iris[['sl','sw','pl', 'pw']])

In [268]:
model_4 = sm.Logit(yvar, Xvar_4)
res_4 = model_4.fit()

predict_4 = np.where(res_4.predict(Xvar_4)>=0.5,1,0)
predict

Optimization terminated successfully.
         Current function value: 0.059493
         Iterations 12


array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [353]:
res_4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       95
Method:                           MLE   Df Model:                            4
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.9142
Time:                        23:12:01   Log-Likelihood:                -5.9493
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 1.947e-26
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -42.6378     25.708     -1.659      0.097     -93.024       7.748
sl            -2.4652      2.394     -1.030      0.303      -7.158       2.228
sw            -6.6809      4.480     -1.491      0.136     -15.461       2.099
pl             9.4294      4.737      1.990      0.047       0.145      18.714
pw            18.2861      9.743      1.877      0.061      -0.809      37.381
==============================================================================

Possibly complete quasi-separation: A fraction 0.60 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [269]:
print(confusion_matrix(yvar,predict_4))

[[49  1]
 [ 1 49]]


#### Apply interaction terms

In [270]:
iris['sw*pl'] = iris['sw']*iris['pl']
iris['sw*pw'] = iris['sw']*iris['pw']
iris['sl*pl'] = iris['sl']*iris['pl']
iris['sl*pw'] = iris['sl']*iris['pw']
iris['pl*pl'] = iris['pl']*iris['pl']
iris['pl*pw'] = iris['pl']*iris['pw']
iris['pw*pw'] = iris['pw']*iris['pw']

In [349]:
Xvar_5 = sm.add_constant(iris[['sl', 'sw', 'pl','pw','sw*sl', 'sw*sw', 'sl*sl', 
                               'sw*pl', 'sw*pw', 'sl*pl', 'sl*pw', 'pl*pl', 'pl*pw', 'pw*pw']])

In [350]:
model_5 = sm.Logit(yvar, Xvar_5)
res_5 = model_5.fit()

predict_5 = np.where(res_5.predict(Xvar_5)>=0.5,1,0)
predict

         Current function value: inf
         Iterations: 35


/Users/mac/opt/anaconda3/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1800: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


LinAlgError: Singular matrix

#### Use some of the interaction terms

In [273]:
Xvar_6 = sm.add_constant(iris[['sl', 'sw', 'sw*sl', 
                               'sw*pl', 'sw*pw', 'sl*pl', 'sl*pw', 'pl*pw']])

In [274]:
model_6 = sm.Logit(yvar, Xvar_6)
res_6 = model_6.fit()

predict_6 = np.where(res_6.predict(Xvar_6)>=0.5,1,0)
predict

Optimization terminated successfully.
         Current function value: 0.056541
         Iterations 14


array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [354]:
res_6.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       91
Method:                           MLE   Df Model:                            8
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.9184
Time:                        23:12:20   Log-Likelihood:                -5.6541
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 1.015e-23
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        167.2483    278.640      0.600      0.548    -378.877     713.373
sl           -53.9411     62.724     -0.860      0.390    -176.877      68.995
sw           -17.0214    140.268     -0.121      0.903    -291.942     257.899
sw*sl         -2.6232     13.764     -0.191      0.849     -29.600      24.354
sw*pl          4.1101     23.470      0.175      0.861     -41.890      50.110
sw*pw          3.6989     29.772      0.124      0.901     -54.654      62.052
sl*pl          5.5842      9.722      0.574      0.566     -13.470      24.638
sl*pw         19.1142     29.435      0.649      0.516     -38.577      76.805
pl*pw        -22.1149     38.481     -0.575      0.565     -97.536      53.306
==============================================================================

Possibly complete quasi-separation: A fraction 0.62 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [275]:
print(confusion_matrix(yvar,predict_6))

[[49  1]
 [ 1 49]]


# 2. Ridge penalty

### (1) Use sl & sw as explanatory variables 

- standardization

In [15]:
x_var = iris[['sl', 'sw']]

x_var = (x_var - x_var.mean())/x_var.std()

In [16]:
R_Xvar_1 = sm.add_constant(x_var)

In [17]:
R_model_1 = sm.Logit(yvar, R_Xvar_1)

#### alpha cross validation : Find alpha which makes the smallest AIC

In [18]:
alpha_cv = np.linspace(0,100,200)
def finding_alpha_using_aic(Ridge_logit, alpha_cv):
    AIC = []
    for i in alpha_cv:
        results = Ridge_logit.fit_regularized(start_params=None,alpha=i,L1_wt =0) # L1_wt = 0 이면 Ridge
        AIC.append(results.aic)
    return alpha_cv[np.argmin(AIC)]

In [19]:
alpha = finding_alpha_using_aic(R_model_1, alpha_cv)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5516285403981525
            Iterations: 17
            Function evaluations: 17
            Gradient evaluations: 17
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.558569764403238
            Iterations: 22
            Function evaluations: 22
            Gradient evaluations: 22
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5651588642523611
            Iterations: 17
            Function evaluations: 17
            Gradient evaluations: 17
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5714836538860392
            Iterations: 13
            Function evaluations: 13
            Gradient evaluations: 13
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5775541800468139
            Iterations: 13
            Function eval

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6929557814775027
            Iterations: 4
            Function evaluations: 4
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931024086164981
            Iterations: 4
            Function evaluations: 4
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
 

            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599453
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.69314718

In [296]:
R_res_1 = R_model_1.fit_regularized(start_paras=None,alpha = alpha, L1_wt =0)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5994731983462268
            Iterations: 12
            Function evaluations: 12
            Gradient evaluations: 12


In [355]:
R_res_1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       99
Method:                           MLE   Df Model:                            0
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.1934
Time:                        23:33:33   Log-Likelihood:                -55.909
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const               0        nan        nan        nan         nan         nan
sl             1.0046      0.265      3.784      0.000       0.484       1.525
sw                  0        nan        nan        nan         nan         nan
==============================================================================
"""

In [297]:
R_predict_1 = np.where(R_res_1.predict(R_Xvar_1)>=0.5,1,0)

In [298]:
R_predict_1

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0])

In [299]:
print(confusion_matrix(yvar,R_predict_1))

[[36 14]
 [13 37]]


### (2) Use sl, sw and put some interaction terms using sl and sw

In [312]:
x_var2 = iris[['sl', 'sw', 'sl*sl', 'sw*sl', 'sw*sw']]

x_var2 = (x_var2 - x_var2.mean())/x_var2.std()

In [313]:
R_Xvar_2 = sm.add_constant(x_var2)

In [314]:
R_model_2 = sm.Logit(yvar, R_Xvar_2)

In [315]:
alpha2 = finding_alpha_using_aic(R_model_2, alpha_cv)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5494827120817407
            Iterations: 50
            Function evaluations: 50
            Gradient evaluations: 50
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5574173548878715
            Iterations: 37
            Function evaluations: 37
            Gradient evaluations: 37
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5640831322293896
            Iterations: 31
            Function evaluations: 31
            Gradient evaluations: 31
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5704398495161961
            Iterations: 26
            Function evaluations: 26
            Gradient evaluations: 26
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5765655558129429
            Iterations: 21
            Function eva

In [316]:
R_res_2 = R_model_2.fit_regularized(start_paras=None,alpha = alpha2, L1_wt =0)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.5640831322293896
            Iterations: 31
            Function evaluations: 31
            Gradient evaluations: 31


In [356]:
R_res_2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       98
Method:                           MLE   Df Model:                            1
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.2049
Time:                        23:33:49   Log-Likelihood:                -55.113
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 9.852e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const               0        nan        nan        nan         nan         nan
sl                  0        nan        nan        nan         nan         nan
sw                  0        nan        nan        nan         nan         nan
sl*sl          1.0735      0.507      2.117      0.034       0.079       2.068
sw*sl          0.2151      0.481      0.447      0.655      -0.727       1.157
sw*sw               0        nan        nan        nan         nan         nan
==============================================================================
"""

In [317]:
R_predict_2 = np.where(R_res_2.predict(R_Xvar_2)>=0.5,1,0)
R_predict_2
print(confusion_matrix(yvar,R_predict_2))

[[38 12]
 [15 35]]


### (3) Use all the data (sl,sw,pl,pw) as explanatory variables 

In [324]:
x_var3 = iris[['sl', 'sw', 'pw', 'pl']]

x_var3 = (x_var3 - x_var3.mean())/x_var3.std()

In [325]:
R_Xvar_3 = sm.add_constant(x_var3)

In [326]:
R_model_3 = sm.Logit(yvar, R_Xvar_3)

In [327]:
alpha3 = finding_alpha_using_aic(R_model_3, alpha_cv)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.05949273395709722
            Iterations: 48
            Function evaluations: 50
            Gradient evaluations: 48
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.122387501583321
            Iterations: 47
            Function evaluations: 47
            Gradient evaluations: 47
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.1631288285668586
            Iterations: 40
            Function evaluations: 40
            Gradient evaluations: 40
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.19488359935937266
            Iterations: 37
            Function evaluations: 37
            Gradient evaluations: 37
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.22164782021132892
            Iterations: 26
            Function e

In [328]:
R_res_3 = R_model_3.fit_regularized(start_paras=None,alpha = alpha3, L1_wt =0)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.05949273395709722
            Iterations: 48
            Function evaluations: 50
            Gradient evaluations: 48


In [357]:
R_res_3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       95
Method:                           MLE   Df Model:                            4
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.9142
Time:                        23:34:06   Log-Likelihood:                -5.9493
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 1.947e-26
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3544      0.841     -0.421      0.673      -2.003       1.294
sl            -1.6340      1.587     -1.030      0.303      -4.745       1.476
sw            -2.2231      1.491     -1.491      0.136      -5.145       0.698
pw             7.7674      4.138      1.877      0.061      -0.344      15.878
pl             7.7847      3.911      1.990      0.047       0.119      15.450
==============================================================================

Possibly complete quasi-separation: A fraction 0.60 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [329]:
R_predict_3 = np.where(R_res_3.predict(R_Xvar_3)>=0.5,1,0)
R_predict_3
print(confusion_matrix(yvar,R_predict_3))

[[49  1]
 [ 1 49]]


In [343]:
x_var4 = iris[['sl', 'sw','pl','pw', 'sl*sl', 'sw*sl', 'sw*sw','sl*pl', 
               'sl*pw', 'sw*pl', 'sw*pw', 'pl*pl', 'pl*pw', 'pw*pw']]

x_var4 = (x_var4 - x_var4.mean())/x_var4.std()

In [344]:
R_Xvar_4 = sm.add_constant(x_var4)

In [345]:
R_model_4 = sm.Logit(yvar, R_Xvar_4)

In [346]:
alpha4 = finding_alpha_using_aic(R_model_4, alpha_cv)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.300672718229014e-10
            Iterations: 163
            Function evaluations: 168
            Gradient evaluations: 163
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.12211914629409487
            Iterations: 118
            Function evaluations: 119
            Gradient evaluations: 118
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.162719410639816
            Iterations: 103
            Function evaluations: 103
            Gradient evaluations: 103
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.19476887761669553
            Iterations: 92
            Function evaluations: 92
            Gradient evaluations: 92
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.2216375351483167
            Iterations: 76
           

In [347]:
R_res_4 = R_model_4.fit_regularized(start_paras=None,alpha = alpha4, L1_wt =0)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.162719410639816
            Iterations: 103
            Function evaluations: 103
            Gradient evaluations: 103


In [358]:
R_res_4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                     sp   No. Observations:                  100
Model:                          Logit   Df Residuals:                       96
Method:                           MLE   Df Model:                            3
Date:                Mon, 12 Apr 2021   Pseudo R-squ.:                  0.8678
Time:                        23:34:31   Log-Likelihood:                -9.1643
converged:                       True   LL-Null:                       -69.315
Covariance Type:            nonrobust   LLR p-value:                 6.647e-26
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const               0        nan        nan        nan         nan         nan
sl                  0        nan        nan        nan         nan         nan
sw                  0        nan        nan        nan         nan         nan
pl             2.8734      1.281      2.243      0.025       0.363       5.384
pw             3.2067      1.172      2.735      0.006       0.909       5.504
sl*sl               0        nan        nan        nan         nan         nan
sw*sl         -0.5490      1.528     -0.359      0.719      -3.544       2.446
sw*sw         -0.4430      1.323     -0.335      0.738      -3.037       2.151
sl*pl               0        nan        nan        nan         nan         nan
sl*pw               0        nan        nan        nan         nan         nan
sw*pl               0        nan        nan        nan         nan         nan
sw*pw               0        nan        nan        nan         nan         nan
pl*pl               0        nan        nan        nan         nan         nan
pl*pw               0        nan        nan        nan         nan         nan
pw*pw               0        nan        nan        nan         nan         nan
==============================================================================
"""

In [348]:
R_predict_4 = np.where(R_res_4.predict(R_Xvar_4)>=0.5,1,0)
R_predict_4
print(confusion_matrix(yvar,R_predict_4))

[[47  3]
 [ 1 49]]


# 3. Possible problems and solutions to correct them in question 1 and 2 

#### 1. When I put all the interaction terms in Question 1- (3), singular matrix problem occured.

#### * Don't use all the variables -> can find that the accuracy in classification increased 
=> Need to delete some of the variables to avoid singular matrix problem

#### 2. Large p-value (small significance of the coefficients)
#### * Need to consider which data to be used in the main estimation

#### 3. When I use ridge penalty, there are "nan" values in some of the data 
#### * When alpha gets big, the value is inclined to converge to zero 

# 4. Explain what is the best model and how can you find the best model

In [359]:
res_1.aic

116.32570807924161

In [360]:
res_2.aic

121.89654241616589

In [362]:
res_3.aic

118.0804450563694

In [363]:
res_4.aic

21.898546791358836

In [365]:
res_6.aic

29.308161560683317

#### When you check AIC, 4th regression seems to be the best model
4th regression contains sl, sw, pl, pw as explanatory variables

In [366]:
R_res_1.aic

113.81728177603921

In [367]:
R_res_2.aic

114.22653150145575

In [368]:
R_res_3.aic

21.89854679141944

In [369]:
R_res_4.aic

26.32856011795308

#### When you check AIC with Ridge penalty, 3rd regression seems to be the best model
3rd regression contains sl, sw, pl, pw as explanatory variables

In [370]:
print(confusion_matrix(yvar,predict_4))
print(confusion_matrix(yvar,R_predict_3))

[[49  1]
 [ 1 49]]
[[49  1]
 [ 1 49]]


### We can chekc the accuracy increased compared to the other specification

#### We can conclude that it is not good to use all the data as explanatory variables 
#### It decreased the significance of estimated results and increased AIC

# 5. References

###### 1. Lecture note
- GLM_2_improved 에 나오는 python 코드 및 위의 R코드의 논리 과정 참고
- STAT_models 에 나오는 R코드의 논리 과정 참고 (lambda 최적화를 구하는 논리)


###### 2. Python code in Google
- logistic regression: https://www.geeksforgeeks.org/logistic-regression-using-statsmodels/
- confusion matrix : https://stackoverflow.com/questions/22520964/getting-pred-table-information-for-predicted-values-of-a-model-in-statsmodels
- normalization : https://rfriend.tistory.com/268
- Ridge penalty: https://stackoverflow.com/questions/64740275/run-lasso-and-ridge-logistic-regression-using-statsmodels-in-python
- Ridge penalty: https://thequackdaddy.github.io/statsmodels.github.io/0.8.0/generated/statsmodels.regression.linear_model.OLS.fit_regularized.html
- Ridge penalty 부과함에 따라 계수값 0에 수렴하는 문제 : https://brunch.co.kr/@itschloe1/11